local Cmp = {
  CmpItemAbbrDeprecated = { fg = C.co, style = "strikethrough" },
  CmpItemAbbrMatch = { fg = C.comment },
  CmpItemAbbrMatchFuzzy = { fg = C.comment },
  CmpItemKindFunction = { fg = C.purple_test_2 },
  CmpItemKindMethod = { fg = C.purple_test_2 },
  CmpItemKindConstructor = { fg = C.orange_new },
  CmpItemKindClass = { fg = C.orange_new },
  CmpItemKindEnum = { fg = C.orange_new },
  CmpItemKindEvent = { fg = C.purple_test_2 },
  CmpItemKindInterface = { fg = C.cc },
  CmpItemKindStruct = { fg = C.vivid_sky_blue },
  CmpItemKindVariable = { fg = C.vivid_sky_blue },
  CmpItemKindField = { fg = C.vivid_sky_blue },
  CmpItemKindProperty = { fg = C.vivid_sky_blue },
  CmpItemKindEnumMember = { fg = C.cc },
  CmpItemKindConstant = { fg = C.vivid_sky_blue },
  CmpItemKindKeyword = { fg = C.gray_new },
  CmpItemKindModule = { fg = C.gray_new },
  CmpItemKindValue = { fg = C.gray_new },
  CmpItemKindUnit = { fg = C.gray_new },
  CmpItemKindText = { fg = C.gray_new },
  CmpItemKindSnippet = { fg = C.gray_new },
  CmpItemKindFile = { fg = C.gray_new },
  CmpItemKindFolder = { fg = C.gray_new },
  CmpItemKindColor = { fg = C.gray_new },
  CmpItemKindReference = { fg = C.gray_new },
  CmpItemKindOperator = { fg = C.gray_new },
  CmpItemKindTypeParameter = { fg = C.gray_new },
}

return Cmp
