local highlights = {
  Bold = { style = "bold" },
  Boolean = { fg = C.blue },
  Character = { fg = C.orange },
  ColorColumn = { bg = C.dark },
  Comment = { fg = C.comment, style = "italic" },
  Conceal = { fg = C.accent },
  Conditional = { fg = C.blue },
  Constant = { fg = C.vivid_sky_blue },
  CursorColumn = { bg = C.dark },
  Cursor = { fg = C.cursor_fg, bg = C.cursor_bg },
  CursorIM = { fg = C.cursor_fg, bg = C.cursor_bg },
  CursorLine = { bg = C.dark },
  CursorLineNr = { fg = C.vivid_sky_blue, style = "bold" },
  Debug = { fg = C.red },
  Define = { fg = C.purple },
  Delimiter = { fg = C.gray },
  DiffAdd = { fg = C.alt_bg, bg = C.sign_add },
  DiffChange = { fg = C.alt_bg, bg = C.sign_change, style = "underline" },
  DiffDelete = { fg = C.alt_bg, bg = C.sign_delete },
  Directory = { fg = C.blue },
  EndOfBuffer = { fg = C.bg },
  Error = { fg = C.error_red, bg = C.bg, style = "bold" },
  ErrorMsg = { fg = C.error_red, bg = C.bg, style = "bold" },
  Exception = { fg = C.purple },
  FloatBorder = { fg = C.purple_test_2, bg = C.alt_bg },
  Float = { fg = C.light_green },
  FoldColumn = { fg = C.accent, bg = C.alt_bg },
  Folded = { fg = C.accent, bg = C.alt_bg },
  Function = { fg = C.yellow },
  Identifier = { fg = C.light_blue },
  Ignore = { fg = C.cyan_test, bg = C.bg, style = "bold" },
  Include = { fg = C.purple },
  IncSearch = { fg = C.search_orange, bg = C.light_gray },
  Italic = { style = "italic" },
  Keyword = { fg = C.blue },
  Label = { fg = C.purple },
  lCursor = { fg = C.cursor_fg, bg = C.cursor_bg },
  LineNr = { fg = C.vivid_sky_blue },
  Macro = { fg = C.purple },
  MatchParenCur = { style = "underline" },
  MatchParen = { fg = C.hint_blue, bg = C.bg, style = "underline" },
  MatchWordCur = { style = "underline" },
  MatchWord = { style = "underline" },
  ModeMsg = { fg = C.blanc, bg = C.dark },
  MoreMsg = { fg = C.orange },
  MsgArea = { fg = C.blanc, bg = Config.transparent_background and "NONE" or C.bg },
  MsgSeparator = { fg = C.blanc, bg = C.bg },
  NonText = { fg = C.bg },
  Normal = { fg = C.blanc, bg = Config.transparent_background and "NONE" or C.bg },
  NormalFloat = { bg = C.dark },
  NormalNC = { fg = C.blanc, bg = Config.transparent_background and "NONE" or C.bg },
  Number = { fg = C.light_green },
  Operator = { fg = C.blanc },
  Pmenu = { fg = C.light_gray, bg = C.tree_gray },
  PmenuSbar = { bg = C.alt_bg },
  PmenuSel = { bg = C.ui2_blue },
  PmenuThumb = { bg = C.gray },
  PreCondit = { fg = C.purple },
  PreProc = { fg = C.purple },
  Question = { fg = C.orange },
  QuickFixLine = { bg = C.ui2_blue },
  Repeat = { fg = C.purple },
  Search = { fg = C.light_gray, bg = C.search_blue },
  SignColumn = { bg = C.bg },
  SpecialChar = { fg = C.white },
  SpecialComment = { fg = C.gray },
  Special = { fg = C.orange },
  SpecialKey = { fg = C.blue, style = "bold" },
  SpellBad = { fg = C.purple_test_2, style = "underline" },
  SpellCap = { fg = C.aureolin, style = "underline" },
  SpellLocal = { fg = C.comment, style = "underline" },
  SpellRare = { fg = C.comment, style = "underline" },
  Statement = { fg = C.purple },
  StorageClass = { fg = C.blue },
  String = { fg = C.orange },
  Structure = { fg = C.blue },
  Substitute = { fg = C.light_gray, bg = C.search_orange },
  TabLine = { fg = C.light_gray, bg = C.alt_bg },
  TabLineFill = { fg = C.alt_bg, bg = C.alt_bg },
  TabLineSel = { fg = C.white, bg = C.alt_bg },
  Tag = { fg = C.blue },
  TermCursor = { fg = C.cursor_fg, bg = C.cursor_bg },
  TermCursorNC = { fg = C.cursor_fg, bg = C.cursor_bg },
  Title = { fg = C.blue, style = "bold" },
  Todo = { fg = C.magenta, bg = C.bg, style = "bold" },
  Typedef = { fg = C.blue },
  Type = { fg = C.cyan_test },
  Underlined = { style = "underline" },
  Variable = { fg = C.light_blue },
  VertSplit = { fg = C.purple_test_2, bg = C.bg },
  Visual = { bg = C.ui_blue },
  VisualNOS = { bg = C.alt_bg },
  WarningMsg = { fg = C.error_red, bg = C.bg },
  Whitespace = { fg = C.bg },
  WildMenu = { fg = C.blanc, bg = C.ui2_blue },
}
return highlights
