local LSP = {
	LspDiagnosticsDefaultError = { fg = C.red_new },
	LspDiagnosticsDefaultWarning = { fg = C.orange_new },
	LspDiagnosticsDefaultInformation = { fg = C.aureolin },
	LspDiagnosticsDefaultInfo = { fg = C.aureolin },
	LspDiagnosticsDefaultHint = { fg = C.vivid_sky_blue },
	LspDiagnosticsVirtualTextError = { fg = C.red_new },
	LspDiagnosticsVirtualTextWarning = { fg = C.orange_new },
	LspDiagnosticsVirtualTextInformation = { fg = C.aureolin },
	LspDiagnosticsVirtualTextInfo = { fg = C.aureolin },
	LspDiagnosticsVirtualTextHint = { fg = C.vivid_sky_blue },
	LspDiagnosticsFloatingError = { fg = C.red_new },
	LspDiagnosticsFloatingWarning = { fg = C.orange_new },
	LspDiagnosticsFloatingInformation = { fg = C.aureolin },
	LspDiagnosticsFloatingInfo = { fg = C.aureolin },
	LspDiagnosticsFloatingHint = { fg = C.vivid_sky_blue },
	DiagnosticSignError = { fg = C.red_new },
	DiagnosticSignWarning = { fg = C.orange_new },
	DiagnosticSignInformation = { fg = C.aureolin },
	DiagnosticSignInfo = { fg = C.aureolin },
	DiagnosticSignHint = { fg = C.vivid_sky_blue },
	LspDiagnosticsSignError = { fg = C.red_new },
	LspDiagnosticsSignWarning = { fg = C.orange_new },
	LspDiagnosticsSignInformation = { fg = C.aureolin },
	LspDiagnosticsSignInfo = { fg = C.aureolin },
	LspDiagnosticsSignHint = { fg = C.vivid_sky_blue },
	LspDiagnosticsError = { fg = C.red_new },
	LspDiagnosticsWarning = { fg = C.orange_new },
	LspDiagnosticsInformation = { fg = C.aureolin },
	LspDiagnosticsInfo = { fg = C.aureolin },
	LspDiagnosticsHint = { fg = C.vivid_sky_blue },
	LspDiagnosticsUnderlineError = { style = "underline" },
	LspDiagnosticsUnderlineWarning = { style = "underline" },
	LspDiagnosticsUnderlineInformation = { style = "underline" },
	LspDiagnosticsUnderlineInfo = { style = "underline" },
	LspDiagnosticsUnderlineHint = { style = "underline" },
	LspReferenceRead = { bg = C.bg_2 },
	LspReferenceText = { bg = C.bg_2 },
	LspReferenceWrite = { bg = C.bg_2 },
}

return LSP
