local markdown = {
  markdownBlockquote = { fg = C.comment },
  markdownCode = { fg = C.orange_new },
  markdownCodeBlock = { fg = C.orange_new },
  markdownCodeDelimiter = { fg = C.orange_new },
  markdownH1 = { fg = C.vivid_sky_blue },
  markdownH2 = { fg = C.vivid_sky_blue },
  markdownH3 = { fg = C.vivid_sky_blue },
  markdownH4 = { fg = C.vivid_sky_blue },
  markdownH5 = { fg = C.vivid_sky_blue },
  markdownH6 = { fg = C.vivid_sky_blue },
  markdownHeadingDelimiter = { fg = C.vivid_sky_blue },
  markdownHeadingRule = { fg = C.fg, style = "bold" },
  markdownId = { fg = C.purple_test_2 },
  markdownIdDeclaration = { fg = C.cc },
  markdownIdDelimiter = { fg = C.gray_new },
  markdownLinkDelimiter = { fg = C.gray_new },
  markdownBold = { fg = C.cc, style = "bold" },
  markdownItalic = { style = "italic" },
  markdownBoldItalic = { fg = C.aurelion, style = "bold,italic" },
  markdownListMarker = { fg = C.cc },
  markdownOrderedListMarker = { fg = C.cc },
  markdownRule = { fg = C.blanc },
  markdownUrl = { fg = C.cyan, style = "underline" },
  markdownLinkText = { fg = C.cc },
  markdownFootnote = { fg = C.orange_new },
  markdownFootnoteDefinition = { fg = C.orange_new },
  markdownEscape = { fg = C.aurelion },
}

return markdown
