local Treesitter = {
	TSComment = { fg = C.comment },
	TSAnnotation = { fg = C.aureolin },
	TSAttribute = { fg = C.vivid_sky_blue },
	TSConstructor = { fg = C.vivid_sky_blue },
	TSType = { fg = C.vivid_sky_blue },
	TSTypeBuiltin = { fg = C.blue },
	TSConditional = { fg = C.blue },
	TSException = { fg = C.purple_test_2 },
	TSInclude = { fg = C.purple_test_2 },
	TSKeywordReturn = { fg = C.purple_test_2 },
	TSKeyword = { fg = C.blue },
	TSKeywordFunction = { fg = C.blue },
	TSLabel = { fg = C.vivid_sky_blue },
	TSNamespace = { fg = C.vivid_sky_blue },
	TSRepeat = { fg = C.purple_test_2 },
	TSConstant = { fg = C.vivid_blue },
	TSConstBuiltin = { fg = C.vivid_blue },
	TSFloat = { fg = C.light_green },
	TSNumber = { fg = C.light_green },
	TSBoolean = { fg = C.blue },
	TSCharacter = { fg = C.orange_new },
	TSError = { fg = C.red_new },
	TSFunction = { fg = C.purple_test_2 },
	TSFuncBuiltin = { fg = C.aureolin },
	TSMethod = { fg = C.aureolin },
	TSConstMacro = { fg = C.vivid_sky_blue },
	TSFuncMacro = { fg = C.aureolin },
	TSVariable = { fg = C.vivid_sky_blue },
	TSVariableBuiltin = { fg = C.vivid_sky_blue },
	TSProperty = { fg = C.vivid_sky_blue },
	TSOperator = { fg = C.gray_new },
	TSField = { fg = C.vivid_sky_blue },
	TSParameter = { fg = C.vivid_sky_blue },
	TSParameterReference = { fg = C.vivid_sky_blue },
	TSSymbol = { fg = C.vivid_sky_blue },
	TSText = { fg = C.gray_new },
	TSPunctDelimiter = { fg = C.gray_new },
	TSTagDelimiter = { fg = C.gray },
	TSTagAttribute = { fg = C.vivid_sky_blue },
	TSPunctBracket = { fg = C.gray_new },
	TSPunctSpecial = { fg = C.blue },
	TSString = { fg = C.orange_new },
	TSStringRegex = { fg = C.orange_new },
	TSTag = { fg = C.blue },
	TSEmphasis = { style = "italic" },
	TSUnderline = { style = "underline" },
	TSTitle = { fg = C.gray_new },
	TSLiteral = { fg = C.orange_new },
	TSURI = { fg = C.orange_new, style = "underline" },
	TSKeywordOperator = { fg = C.blue },
	TSStructure = { fg = C.vivid_sky_blue },
	TSStrong = { fg = C.blue, style = "bold" },
	TSQueryLinterError = { fg = C.ore },
	TreesitterContext = { bg = C.cy },
}

return Treesitter
